### ISSUE TITLE
交互模式确定

### ISSUE THREAD

**Issue by littlecodersh** [littlecodersh/danmu#1]
@tempdban 
兄弟，我在想这个包应该做成什么样子给用户使用。
没找到什么好的想法，有什么建议吗？

**Comment by tempdban** [comment]
所以说我觉得itchat 抽象的还不够，既然都是文本消息，两块代码其实就有很多公用的部分。做成一个平台，拆成模块，比方说控制台模块、微信接口、弹幕接口、自动回复模块。这些模块可以单独按装。这样最终形态只写一个py文件将这些模块组装起来。这样也方便此后再添加功能组件。

**Comment by littlecodersh** [comment]
@tempdban 不考虑背后的实现，能写一些使用代码的示例吗？

**Comment by tempdban** [comment]
from itchat import itchat_bridge
from console import console_bridge
import Manager

itchat = itchat_bridge()
itchat.settings(a='', b='')

console = console_bridge()
console.settings(a='', b='')

manager = Manager()
manager.add_bridge(itchat)
manager.add_bridge(console)

manager.run()

**Comment by littlecodersh** [comment]
@tempdban console这一块是什么意思？

**Comment by tempdban** [comment]
交互方式可选-console和robot，console对应控制台手动交互，robot表示ai自动交互

**Comment by tempdban** [comment]
而且弹幕的房间可以映射成微信群

**Comment by littlecodersh** [comment]
@tempdban 那console 和 robot这块要怎么自定义操作？

**Comment by tempdban** [comment]
concole就不用管了，控制台直接敲文字就行
robot 可以带个回调啊，或者可以继承robot，我们只是写个可用的例子

**Comment by littlecodersh** [comment]
了解
