### ISSUE TITLE
斗鱼弹幕部分失效

### ISSUE THREAD

**Issue by rgwt123** [littlecodersh/danmu#21]
socket收到的只有type@=dgb的，即只能收到礼物和其他

![1](https://user-images.githubusercontent.com/22995589/28583341-6abff15c-719b-11e7-8b20-3da7e2f9e59e.JPG)
![default](https://user-images.githubusercontent.com/22995589/28583349-707f7a04-719b-11e7-8eab-9688d24ab110.JPG)

是服务器分开了吗

**Comment by rgwt123** [comment]
自己抓了个地址
221.229.163.130
展示可以用

**Comment by laoyuan** [comment]
把这个IP替换到哪里？

**Comment by laoyuan** [comment]
查到了 openbarrage.douyutv.com
