### ISSUE TITLE
运行后无反应，一段时间后报错

### ISSUE THREAD

**Issue by ma125125t** [littlecodersh/danmu#5]
fangs-mac:danmu fang$ python3 a.py
^CTraceback (most recent call last):
  File "a.py", line 24, in <module>
    dmc.start(blockThread = True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/danmu/__init__.py", line 55, in start
    self.__client.start()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/danmu/Abstract.py", line 29, in start
    time.sleep(self.anchorStatusRescanTime)
KeyboardInterrupt

**Comment by littlecodersh** [comment]
@ma125125t 把使用的代码也发一下吧

**Comment by ma125125t** [comment]
import time, sys

from danmu import DanMuClient

def pp(msg):
    print(msg.encode(sys.stdin.encoding, 'ignore').
        decode(sys.stdin.encoding))

dmc = DanMuClient('http://www.douyu.com/787579')
if not dmc.isValid(): print('Url not valid')

@dmc.danmu
def danmu_fn(msg):
    pp('[%s] %s' % (msg['NickName'], msg['Content']))

@dmc.gift
def gift_fn(msg):
    pp('[%s] sent a gift!' % content['NickName'])

@dmc.other
def other_fn(msg):
    pp('Other message received')

dmc.start(blockThread = True)

**Comment by littlecodersh** [comment]
@ma125125t 我这里使用没有问题，你尝试更新一下danmu的版本
```bash
pip install danmu --upgrade
```
