### ISSUE TITLE
礼物消息没有截获到

### ISSUE THREAD

**Issue by littleweb** [littlecodersh/danmu#6]
**问题描述：**

斗鱼，全民，熊猫，战旗这4个平台测试了有50个主播，都只能截获到普通danmu消息，礼物的截获不到，求大神指教

**系统：**

centos6.5

**代码：**

```python
@dmc.danmu
def danmu_fn(msg):
    payload = {
        "star_id": star_id,
        "text": msg['Content'],
        "type": "danmu",
        "plat": plat
    }
    r = requests.get("http://localhost:9203/save", params=payload)
@dmc.gift
def gift_fn(msg):
    pp('[%s] sent a gift!' % content['NickName'])
    payload = {
        "star_id": star_id,
        "text": "gift",
        "type": "gift",
        "plat": plat
    }
    r = requests.get("http://localhost:9203/save", params=payload)
@dmc.other
def other_fn(msg):
    pp('Other message received')

dmc.start(blockThread = True)
```

**Comment by littlecodersh** [comment]
@littleweb 代码不完整，建议补全

**Comment by littleweb** [comment]
# -*- coding: UTF-8 -*-
import time, sys, requests

from danmu import DanMuClient

star_url = "http://www.douyu.com/wt55kai"


def pp(msg):
    print(msg.encode(sys.stdin.encoding, 'ignore').
        decode(sys.stdin.encoding))
    sys.stdout.flush()

dmc = DanMuClient(star_url)
if not dmc.isValid(): print('Url not valid')

@dmc.danmu
def danmu_fn(msg):
    payload = {
            "star_id": "star_id",
            "text": msg['Content'],
            "type": "danmu",
            "plat": "plat"
        }
    print payload

@dmc.gift
def gift_fn(msg):
    pp('[%s] sent a gift!' % content['NickName'])
    payload = {
            "star_id": "star_id",
            "text": msg['Content'],
            "type": "danmu",
            "plat": "plat"
        }
    print payload

@dmc.other
def other_fn(msg):
    pp('Other message received')

dmc.start(blockThread = True)

**Comment by littlecodersh** [comment]
@littleweb 
我这里获取正常没有问题。
另，gift的Content键是没有内容的。

**Comment by littleweb** [comment]
我把代码精简了下，还是只能打印出danmu，gift打印不出呢。
import time, sys, requests

from danmu import DanMuClient

star_url = "http://www.douyu.com/wt55kai"

dmc = DanMuClient(star_url)
if not dmc.isValid(): print('Url not valid')

@dmc.danmu
def danmu_fn(msg):
    print "danmu";

@dmc.gift
def gift_fn(msg):
    print "gift";

@dmc.other
def other_fn(msg):
    print('Other message received')

dmc.start(blockThread = True)

**Comment by littlecodersh** [comment]
@littleweb 
* 你的danmu包版本是多少？
* 我这里能够获取说明协议没有问题
* 弹幕能获取说明通信与启动没有问题
* 建议抓个包看一下是否收到了弹幕的相关消息

**Comment by littleweb** [comment]
OK了，应该是语法问题，多谢

**Comment by littlecodersh** [comment]
@littleweb 
哪段代码的语法问题？我没有看出来
不同平台数量的算法不一样的，你可以获取整个消息体研究一下。

**Comment by littleweb** [comment]
payload = {
            "star_id": "star_id",
            "text": msg['Content'],
            "type": "danmu",
            "plat": "plat"
        }
    print payload


我把这块封装了一下就好了

**Comment by littlecodersh** [comment]
@littleweb 
为什么封装一下就好了？
另，不是[精简的代码][simplized_code]也同样打不出来吗？

[simplized_code]: https://github.com/littlecodersh/danmu/issues/6#issuecomment-240094789

**Comment by littleweb** [comment]
有可能调试的时候正好没有礼物吧

**Comment by littlecodersh** [comment]
@littleweb 
好的，那封装是指？

**Comment by littleweb** [comment]
def save(type,text):
    payload = {
            "star_id": star_id,
            "text": text,
            "type": type,
            "plat": plat
        }
    r = requests.get("http://localhost:9203/save", params=payload)

dmc = DanMuClient(star_url)
if not dmc.isValid(): print('Url not valid')

@dmc.danmu
def danmu_fn(msg):
    save("danmu",msg['Content'])
    pp('danmu')

@dmc.gift
def gift_fn(msg):
    save("gift","")
    pp('gift')

@dmc.other
def other_fn(msg):
    pp('Other message received')

dmc.start(blockThread = True)


这样就可以了，很奇怪
