### ISSUE TITLE
能不能把用户的基础熟悉全部获取到

### ISSUE THREAD

**Issue by hifuck** [littlecodersh/danmu#7]
斗鱼可以更改用户名,但是获取弹幕的时候没有获取uid

**Comment by littlecodersh** [comment]
@hifuck 需要你自己研究了，这只是个弹幕包

**Comment by hifuck** [comment]
好吧,我看下python语法先,作者回复的真快啊

**Comment by littlecodersh** [comment]
@hifuck 挺巧的，刚好我在刷github。
斗鱼的话我这里用的是官方提供的第二版的弹幕协议，你可以在他们论坛先找协议下来看一下。
网上还有野路子的模拟的获取方法，你可以在[知乎][zhihu-douyu]上面看一下。

[zhihu-douyu]: http://zhihu.com/question/29027665/answer/45024384
