### ISSUE TITLE
可否添加启动弹幕的同时打开播放器

### ISSUE THREAD

**Issue by yuyangzxw** [littlecodersh/danmu#9]
比如我安装了mpv,youtube-dl

运行 python run.py 后,同时运行 mpv https://www.douyu.com/32892 来打开播放器观看在线视频

谢谢楼主提供的好软件

**Comment by CuGBabyBeaR** [comment]
python 脚本支持运行命令行或者shell命令啊

**Comment by littlecodersh** [comment]
@yuyangzxw 是的，可以设置：
```python
dmc.start(blockThread=False)
```
之后启动相应的播放器。
